#!/bin/sh

if echo "$2" | /bin/grep -q "wireless"; then { /jffs/scripts/wlboost service_event "$@" & }; fi # wlboost
# if echo "$2" | /bin/grep -q "scmerlin"; then { /jffs/scripts/scmerlin service_event "$@" & }; fi # scMerlin
