#!/bin/sh

# Use at your own risk. This script is provided as-is without any warranty.
# This script may be used for testing, in most cases the wlupdate script should work fine.

# Force 5GHz-1 specs
wl -i eth6 down
wl -i eth6 country ALL
wl -i eth6 country_abbrev_override "US"
wl -i eth6 regulatory 1
wl -i eth6 chanspec 149/160
wl -i eth6 up
wl -i eth6 5g_rate auto
wl -i eth6 txpwr1 -o -m 1496

# On an AiMesh node, and if supported, you can use the following commands to force the 5GHz-2 (radio-2) specs:

# Force 5GHz-2 spec (if available)
# wl -i eth6 down
# wl -i eth6 country ALL
# wl -i eth6 country_abbrev_override "US"
# wl -i eth6 regulatory 1
# wl -i eth6 chanspec 149/160
# wl -i eth6 up
# wl -i eth6 5g_rate auto
# wl -i eth6 txpwr1 -o -m 1496
