#!/bin/sh

# Use at your own risk. This script is provided as-is without any warranty.
# Tested with ASUS RT-AX58U v1 (Asuswrt-Merlin) + ASUS ZenWiFi AX XT8 v2 (AiMesh node - stock firmware).
# Please adjusts the given nvram variables (nvram dump) with values of your own device.
# See based source for more details: https://github.com/RMerl/asuswrt-merlin.ng

# Force 5GHz-1 specs
wl -i eth6 down
wl -i eth6 country ALL
wl -i eth6 country_abbrev_override "US"
wl -i eth6 regulatory 1
wl -i eth6 chanspec 149/160
wl -i eth6 up
wl -i eth6 5g_rate auto
wl -i eth6 txpwr1 -o -m 1496